wall_no_pieces = "pictures/wall/wall_no_pieces/"
wall_pieces = "pictures/wall/wall_pieces/"
wall_save = "pictures/wall/save_wall_diff/"
save_parameters_wall_top = "info_data/trackbaretop.txt"
save_parameters_wall_bot = "info_data/trackbarebot.txt"
